### ISSUE TITLE
Voice Recording - Components On A Grid

### ISSUE THREAD

**Issue by Cili23** [Cili23/components-on-a-grid#1]
@thatkidmadrid

https://user-images.githubusercontent.com/77252057/134811532-f52a74f2-83b2-43b6-9d9d-f0f0bb09f1b2.mp4

**Comment by thatkidmadrid** [comment]
looks and sounds good 👍 
nothing to say about the spoken part,  but for the code I notice you've set up the `grid-template-areas` properly and you're using the grid-area properly for the `.pano`, but then not using it on the figures and other grid items. 

For example
```
nav {
  grid-area: banner;
  grid-column: 2;
  grid-row: 1;
}
```

the `grid-area` and the `grid-column/row` are both trying to position the element somewhere on the grid defined in `body`, but because the `grid-column/row` appear after, they override what `grid-area` is trying to do

Anyways, it's not a big deal and you were able to match the reference so full marks 🎉
